-- New table for POST /coupons/validate. Not in the original V1 schema, and the contract itself says so
-- (API_CONTRACT_V1.1.md: "product requirements include coupons ... but some provider-specific payment behavior
-- is not defined by the schema"). Added now as part of building out Subscriptions.
--
-- redemption_count is a global counter, incremented when a coupon is actually applied at checkout
-- (subscriptions.service.SubscriptionService) - there is no per-subscription or per-payment coupon reference
-- column on the approved subscription/payment tables, and this migration does not add one to them, so which
-- specific subscription used a coupon is not individually tracked, only the running total against
-- max_redemptions. applicable_plan_code is a soft reference (not a FK) to plan.code, nullable meaning "valid
-- for any plan".
CREATE TABLE coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(12, 2) NOT NULL,
    applicable_plan_code VARCHAR(50),
    max_redemptions INTEGER,
    redemption_count INTEGER NOT NULL DEFAULT 0,
    starts_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_coupon_discount_type CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT chk_coupon_discount_value CHECK (discount_value > 0)
);

CREATE INDEX idx_coupon_active ON coupon (is_active, expires_at);
