-- Pavitra Ristaa approved schema v1.1 (52 tables).
-- Table "user" is quoted because USER is a PostgreSQL reserved word.

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_system BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    email VARCHAR(255),
    mobile VARCHAR(20),
    password_hash VARCHAR(255),
    account_status VARCHAR(30) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mobile_verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    failed_login_attempts SMALLINT NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_user_account_status CHECK (account_status IN (
        'PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'BLOCKED', 'DELETED'
    ))
);

CREATE UNIQUE INDEX uq_user_email ON "user" (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX uq_user_mobile ON "user" (mobile) WHERE mobile IS NOT NULL;
CREATE INDEX idx_user_account_status ON "user" (account_status);
CREATE INDEX idx_user_created_at ON "user" (created_at);

CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    role_id BIGINT NOT NULL REFERENCES role (id),
    assigned_at TIMESTAMPTZ NOT NULL,
    assigned_by BIGINT REFERENCES "user" (id),
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX idx_user_role_role_id ON user_role (role_id);

CREATE TABLE relationship_mode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE user_relationship_mode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    relationship_mode_id BIGINT NOT NULL REFERENCES relationship_mode (id),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_user_relationship_mode UNIQUE (user_id, relationship_mode_id)
);

CREATE INDEX idx_user_relationship_mode_mode ON user_relationship_mode (relationship_mode_id);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    device_name VARCHAR(255),
    platform VARCHAR(20),
    app_version VARCHAR(30),
    push_token VARCHAR(500),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    CONSTRAINT chk_refresh_token_platform CHECK (platform IS NULL OR platform IN ('WEB', 'IOS', 'ANDROID'))
);

CREATE INDEX idx_refresh_token_user_id ON refresh_token (user_id);
CREATE INDEX idx_refresh_token_expires_at ON refresh_token (expires_at);
CREATE INDEX idx_refresh_token_user_revoked ON refresh_token (user_id, revoked_at);

CREATE TABLE otp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES "user" (id),
    purpose VARCHAR(40) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    otp_hash VARCHAR(255) NOT NULL,
    attempt_count SMALLINT NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_otp_purpose CHECK (purpose IN (
        'REGISTER', 'LOGIN', 'FORGOT_PASSWORD', 'CHANGE_EMAIL', 'CHANGE_MOBILE'
    ))
);

CREATE INDEX idx_otp_destination_purpose_created ON otp (destination, purpose, created_at);
CREATE INDEX idx_otp_user_id ON otp (user_id);

CREATE TABLE login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES "user" (id),
    refresh_token_id BIGINT REFERENCES refresh_token (id),
    login_type VARCHAR(30) NOT NULL,
    ip_address INET,
    user_agent TEXT,
    success BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    login_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_login_type CHECK (login_type IN ('PASSWORD', 'OTP', 'REFRESH'))
);

CREATE INDEX idx_login_history_user_login_at ON login_history (user_id, login_at);
CREATE INDEX idx_login_history_ip_login_at ON login_history (ip_address, login_at);

CREATE TABLE master_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE master_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES master_category (id),
    code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB,
    CONSTRAINT uq_master_value_category_code UNIQUE (category_id, code)
);

CREATE INDEX idx_master_value_category_active ON master_value (category_id, is_active);

CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES "user" (id),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    display_name VARCHAR(150),
    date_of_birth DATE NOT NULL,
    gender VARCHAR(30) NOT NULL,
    headline VARCHAR(200),
    about_me TEXT,
    profile_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    profile_completion_percent SMALLINT NOT NULL DEFAULT 0,
    country_id BIGINT REFERENCES master_value (id),
    state_id BIGINT REFERENCES master_value (id),
    city_id BIGINT REFERENCES master_value (id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_profile_status CHECK (profile_status IN ('DRAFT', 'ACTIVE', 'HIDDEN', 'UNDER_REVIEW'))
);

CREATE INDEX idx_user_profile_gender ON user_profile (gender);
CREATE INDEX idx_user_profile_dob ON user_profile (date_of_birth);
CREATE INDEX idx_user_profile_city ON user_profile (city_id);
CREATE INDEX idx_user_profile_status ON user_profile (profile_status);

CREATE TABLE profile_education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    education_level_id BIGINT REFERENCES master_value (id),
    institution_name VARCHAR(255),
    field_of_study VARCHAR(255),
    graduation_year SMALLINT,
    additional_details TEXT
);

CREATE TABLE profile_career (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    occupation_id BIGINT REFERENCES master_value (id),
    job_title VARCHAR(150),
    company_name VARCHAR(255),
    industry_id BIGINT REFERENCES master_value (id),
    work_location_city_id BIGINT REFERENCES master_value (id),
    experience_years NUMERIC(4, 1),
    is_employed BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE profile_family (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    family_type VARCHAR(50),
    parents_status VARCHAR(50),
    siblings_count SMALLINT,
    family_description TEXT,
    family_values VARCHAR(100)
);

CREATE TABLE profile_lifestyle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    diet_id BIGINT REFERENCES master_value (id),
    smoking_id BIGINT REFERENCES master_value (id),
    drinking_id BIGINT REFERENCES master_value (id),
    exercise_frequency_id BIGINT REFERENCES master_value (id),
    sleep_pattern VARCHAR(50),
    pets BOOLEAN
);

CREATE TABLE spiritual_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    spiritual_community TEXT,
    spiritual_interests TEXT,
    practices TEXT,
    any_spiritual_profession VARCHAR(255),
    dream_spiritual_pilgrimage_destination VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE media_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    owner_user_id BIGINT NOT NULL REFERENCES "user" (id),
    storage_provider VARCHAR(30) NOT NULL,
    bucket VARCHAR(255) NOT NULL,
    object_key VARCHAR(1000) NOT NULL UNIQUE,
    original_filename VARCHAR(255),
    mime_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    checksum VARCHAR(128),
    width INTEGER,
    height INTEGER,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_media_status CHECK (status IN ('UPLOADING', 'ACTIVE', 'QUARANTINED', 'DELETED')),
    CONSTRAINT chk_storage_provider CHECK (storage_provider IN ('S3', 'MINIO'))
);

CREATE INDEX idx_media_file_owner_created ON media_file (owner_user_id, created_at);
CREATE INDEX idx_media_file_status ON media_file (status);

CREATE TABLE profile_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    media_file_id BIGINT NOT NULL REFERENCES media_file (id),
    photo_type VARCHAR(30) NOT NULL,
    display_order SMALLINT NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    visibility VARCHAR(30) NOT NULL DEFAULT 'PUBLIC',
    approval_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_photo_type CHECK (photo_type IN ('PROFILE', 'ADDITIONAL')),
    CONSTRAINT chk_photo_visibility CHECK (visibility IN ('PUBLIC', 'MATCHES', 'PRIVATE')),
    CONSTRAINT chk_photo_approval CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_profile_photo_profile_order ON profile_photo (profile_id, display_order);
CREATE UNIQUE INDEX uq_profile_photo_primary ON profile_photo (profile_id) WHERE is_primary = TRUE;

CREATE TABLE profile_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    verification_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    verified_at TIMESTAMPTZ,
    verified_by BIGINT REFERENCES "user" (id),
    verification_type VARCHAR(50),
    notes TEXT
);

CREATE TABLE profile_language (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    language_id BIGINT NOT NULL REFERENCES master_value (id),
    proficiency VARCHAR(30),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_profile_language UNIQUE (profile_id, language_id)
);

CREATE TABLE profile_interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    interest_id BIGINT NOT NULL REFERENCES master_value (id),
    CONSTRAINT uq_profile_interest UNIQUE (profile_id, interest_id)
);

CREATE TABLE profile_hobby (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    hobby_id BIGINT NOT NULL REFERENCES master_value (id),
    CONSTRAINT uq_profile_hobby UNIQUE (profile_id, hobby_id)
);

CREATE TABLE partner_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES user_profile (id),
    min_age SMALLINT,
    max_age SMALLINT,
    min_height_cm SMALLINT,
    max_height_cm SMALLINT,
    preferred_gender VARCHAR(30),
    min_income NUMERIC(14, 2),
    max_income NUMERIC(14, 2),
    currency_code CHAR(3),
    preferred_marital_status_id BIGINT REFERENCES master_value (id),
    location_radius_km INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE partner_preference_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_preference_id BIGINT NOT NULL REFERENCES partner_preference (id),
    preference_type VARCHAR(50) NOT NULL,
    master_value_id BIGINT NOT NULL REFERENCES master_value (id),
    CONSTRAINT uq_partner_preference_value UNIQUE (partner_preference_id, preference_type, master_value_id)
);

CREATE INDEX idx_partner_preference_value_type ON partner_preference_value (preference_type, master_value_id);

CREATE TABLE profile_view (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_user_id BIGINT NOT NULL REFERENCES "user" (id),
    viewed_profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    viewed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_profile_view_viewed ON profile_view (viewed_profile_id, viewed_at);
CREATE INDEX idx_profile_view_viewer ON profile_view (viewer_user_id, viewed_at);

CREATE TABLE favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_favorite UNIQUE (user_id, profile_id)
);

CREATE INDEX idx_favorite_user_id ON favorite (user_id);

CREATE TABLE saved_search (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    name VARCHAR(150) NOT NULL,
    criteria JSONB NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    criteria JSONB NOT NULL,
    searched_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_search_history_user ON search_history (user_id, searched_at);

CREATE TABLE recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    recommended_profile_id BIGINT NOT NULL REFERENCES user_profile (id),
    relationship_mode_id BIGINT REFERENCES relationship_mode (id),
    score NUMERIC(6, 3),
    reason VARCHAR(255),
    generated_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE INDEX idx_recommendation_user_status ON recommendation (user_id, status, generated_at);
CREATE INDEX idx_recommendation_profile ON recommendation (recommended_profile_id);

CREATE TABLE interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    sender_user_id BIGINT NOT NULL REFERENCES "user" (id),
    receiver_user_id BIGINT NOT NULL REFERENCES "user" (id),
    relationship_mode_id BIGINT NOT NULL REFERENCES relationship_mode (id),
    status VARCHAR(30) NOT NULL,
    message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    responded_at TIMESTAMPTZ,
    CONSTRAINT chk_interest_not_self CHECK (sender_user_id <> receiver_user_id),
    CONSTRAINT chk_interest_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', 'EXPIRED'))
);

CREATE INDEX idx_interest_receiver_status ON interest (receiver_user_id, status);
CREATE INDEX idx_interest_sender_status ON interest (sender_user_id, status);
CREATE INDEX idx_interest_mode ON interest (relationship_mode_id);

CREATE TABLE interest_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interest_id BIGINT NOT NULL REFERENCES interest (id),
    old_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    changed_by BIGINT NOT NULL REFERENCES "user" (id),
    changed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_a_id BIGINT NOT NULL REFERENCES "user" (id),
    user_b_id BIGINT NOT NULL REFERENCES "user" (id),
    relationship_mode_id BIGINT NOT NULL REFERENCES relationship_mode (id),
    source_interest_id BIGINT REFERENCES interest (id),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    matched_at TIMESTAMPTZ NOT NULL,
    unmatched_at TIMESTAMPTZ,
    CONSTRAINT chk_match_not_self CHECK (user_a_id <> user_b_id),
    CONSTRAINT chk_match_status CHECK (status IN ('ACTIVE', 'UNMATCHED')),
    CONSTRAINT chk_match_user_order CHECK (user_a_id < user_b_id),
    CONSTRAINT uq_match_pair_mode UNIQUE (user_a_id, user_b_id, relationship_mode_id)
);

CREATE INDEX idx_match_user_a ON match (user_a_id);
CREATE INDEX idx_match_user_b ON match (user_b_id);

CREATE TABLE block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id BIGINT NOT NULL REFERENCES "user" (id),
    blocked_user_id BIGINT NOT NULL REFERENCES "user" (id),
    reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_block UNIQUE (blocker_user_id, blocked_user_id),
    CONSTRAINT chk_block_not_self CHECK (blocker_user_id <> blocked_user_id)
);

CREATE TABLE report_reason (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    conversation_type VARCHAR(30) NOT NULL DEFAULT 'DIRECT',
    match_id BIGINT REFERENCES match (id),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_conversation_type CHECK (conversation_type IN ('DIRECT', 'GROUP')),
    CONSTRAINT chk_conversation_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'CLOSED'))
);

CREATE INDEX idx_conversation_match ON conversation (match_id);
CREATE INDEX idx_conversation_updated ON conversation (updated_at);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    conversation_id BIGINT NOT NULL REFERENCES conversation (id),
    sender_user_id BIGINT NOT NULL REFERENCES "user" (id),
    message_type VARCHAR(30) NOT NULL DEFAULT 'TEXT',
    content TEXT,
    reply_to_message_id BIGINT REFERENCES message (id),
    status VARCHAR(30) NOT NULL DEFAULT 'SENT',
    sent_at TIMESTAMPTZ NOT NULL,
    edited_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_message_type CHECK (message_type IN ('TEXT', 'IMAGE', 'FILE', 'SYSTEM')),
    CONSTRAINT chk_message_status CHECK (status IN ('SENT', 'DELIVERED', 'DELETED'))
);

CREATE INDEX idx_message_conversation_id ON message (conversation_id, id);
CREATE INDEX idx_message_sender_sent ON message (sender_user_id, sent_at);
CREATE INDEX idx_message_sent_at ON message (sent_at);

CREATE TABLE conversation_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversation (id),
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    joined_at TIMESTAMPTZ NOT NULL,
    left_at TIMESTAMPTZ,
    last_read_message_id BIGINT REFERENCES message (id),
    CONSTRAINT uq_conversation_participant UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_conversation_participant_user ON conversation_participant (user_id);

CREATE TABLE message_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES message (id),
    media_file_id BIGINT NOT NULL REFERENCES media_file (id),
    display_order SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_message_attachment_message ON message_attachment (message_id);

CREATE TABLE message_read (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES message (id),
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    CONSTRAINT uq_message_read UNIQUE (message_id, user_id)
);

CREATE INDEX idx_message_read_user ON message_read (user_id, read_at);

CREATE TABLE message_reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES message (id),
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    reaction_code VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_message_reaction UNIQUE (message_id, user_id)
);

CREATE TABLE report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    reporter_user_id BIGINT NOT NULL REFERENCES "user" (id),
    reported_user_id BIGINT REFERENCES "user" (id),
    reported_message_id BIGINT REFERENCES message (id),
    reason_id BIGINT NOT NULL REFERENCES report_reason (id),
    details TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    resolved_by BIGINT REFERENCES "user" (id),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_report_status CHECK (status IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED'))
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    reference_type VARCHAR(50),
    reference_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_notification_user_read ON notification (user_id, is_read, created_at);

CREATE TABLE notification_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    notification_type VARCHAR(50) NOT NULL,
    in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    push_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sms_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_notification_setting UNIQUE (user_id, notification_type)
);

CREATE TABLE plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    billing_period VARCHAR(20) NOT NULL,
    duration_days INTEGER NOT NULL,
    features JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_billing_period CHECK (billing_period IN ('MONTHLY', 'QUARTERLY', 'YEARLY', 'ONE_TIME'))
);

CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    plan_id BIGINT NOT NULL REFERENCES plan (id),
    status VARCHAR(30) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ,
    auto_renew BOOLEAN NOT NULL DEFAULT FALSE,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_subscription_status CHECK (status IN ('PENDING', 'ACTIVE', 'PAUSED', 'EXPIRED', 'CANCELLED'))
);

CREATE INDEX idx_subscription_user_status ON subscription (user_id, status);
CREATE INDEX idx_subscription_ends_at ON subscription (ends_at);

CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    subscription_id BIGINT REFERENCES subscription (id),
    provider VARCHAR(50) NOT NULL,
    provider_payment_id VARCHAR(255),
    amount NUMERIC(12, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_method VARCHAR(50),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_payment_status CHECK (status IN ('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE UNIQUE INDEX uq_payment_provider_id ON payment (provider, provider_payment_id)
    WHERE provider_payment_id IS NOT NULL;
CREATE INDEX idx_payment_user_created ON payment (user_id, created_at);
CREATE INDEX idx_payment_status ON payment (status);

CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    subscription_id BIGINT REFERENCES subscription (id),
    payment_id BIGINT REFERENCES payment (id),
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL,
    tax_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_invoice_status CHECK (status IN ('ISSUED', 'PAID', 'VOID'))
);

CREATE TABLE media_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_file_id BIGINT NOT NULL REFERENCES media_file (id),
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    access_type VARCHAR(30) NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    CONSTRAINT uq_media_access UNIQUE (media_file_id, user_id, access_type),
    CONSTRAINT chk_media_access_type CHECK (access_type IN ('VIEW', 'DOWNLOAD'))
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES "user" (id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id BIGINT,
    ip_address INET,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_audit_log_actor ON audit_log (actor_user_id, created_at);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_log_created ON audit_log (created_at);

CREATE TABLE support_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    category VARCHAR(50) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    assigned_to BIGINT REFERENCES "user" (id),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_ticket_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT chk_ticket_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT'))
);

CREATE INDEX idx_support_ticket_user_status ON support_ticket (user_id, status);
CREATE INDEX idx_support_ticket_assigned ON support_ticket (assigned_to, status);

CREATE TABLE moderation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    target_user_id BIGINT REFERENCES "user" (id),
    target_profile_id BIGINT REFERENCES user_profile (id),
    target_media_id BIGINT REFERENCES media_file (id),
    target_message_id BIGINT REFERENCES message (id),
    source_report_id BIGINT REFERENCES report (id),
    action VARCHAR(50) NOT NULL,
    reason TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    moderator_user_id BIGINT REFERENCES "user" (id),
    created_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT chk_moderation_action CHECK (action IN ('WARN', 'HIDE', 'SUSPEND', 'BLOCK', 'REMOVE')),
    CONSTRAINT chk_moderation_status CHECK (status IN ('OPEN', 'RESOLVED'))
);

CREATE INDEX idx_moderation_target_user ON moderation (target_user_id, status);
CREATE INDEX idx_moderation_status_created ON moderation (status, created_at);

CREATE TABLE system_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(150) NOT NULL UNIQUE,
    setting_value TEXT,
    value_type VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by BIGINT REFERENCES "user" (id),
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_setting_value_type CHECK (value_type IN ('STRING', 'INTEGER', 'BOOLEAN', 'JSON'))
);
