-- Starter master data. Values can be added later without code changes; codes are stable identifiers.
-- Geography (state/city) is seeded for India only and links to its parent through metadata.

INSERT INTO master_category (code, name, description, is_active) VALUES
    ('COUNTRY', 'Country', 'Countries', TRUE),
    ('STATE', 'State / Region', 'States, provinces and union territories', TRUE),
    ('CITY', 'City', 'Cities and towns', TRUE),
    ('LANGUAGE', 'Language', 'Spoken languages', TRUE),
    ('RELIGION', 'Religion', 'Religion or belief system', TRUE),
    ('EDUCATION_LEVEL', 'Education level', 'Highest education attained', TRUE),
    ('OCCUPATION', 'Occupation', 'Profession or occupation', TRUE),
    ('INDUSTRY', 'Industry', 'Industry / sector of work', TRUE),
    ('MARITAL_STATUS', 'Marital status', 'Marital status', TRUE),
    ('DIET', 'Diet', 'Dietary preference', TRUE),
    ('SMOKING', 'Smoking', 'Smoking habits', TRUE),
    ('DRINKING', 'Drinking', 'Drinking habits', TRUE),
    ('EXERCISE_FREQUENCY', 'Exercise frequency', 'How often the person exercises', TRUE),
    ('INTEREST', 'Interest', 'General interests', TRUE),
    ('HOBBY', 'Hobby', 'Hobbies and activities', TRUE);

-- COUNTRY
INSERT INTO master_value (category_id, code, name, display_order, metadata)
SELECT c.id, v.code, v.name, v.display_order, v.metadata::jsonb
FROM master_category c
CROSS JOIN (VALUES
    ('IN', 'India', 1, NULL),
    ('US', 'United States', 2, NULL),
    ('GB', 'United Kingdom', 3, NULL),
    ('CA', 'Canada', 4, NULL),
    ('AU', 'Australia', 5, NULL),
    ('AE', 'United Arab Emirates', 6, NULL),
    ('SG', 'Singapore', 7, NULL),
    ('DE', 'Germany', 8, NULL),
    ('NZ', 'New Zealand', 9, NULL),
    ('NP', 'Nepal', 10, NULL)
) AS v(code, name, display_order, metadata)
WHERE c.code = 'COUNTRY';

-- STATE (India)
INSERT INTO master_value (category_id, code, name, display_order, metadata)
SELECT c.id, v.code, v.name, v.display_order, '{"countryCode": "IN"}'::jsonb
FROM master_category c
CROSS JOIN (VALUES
    ('IN-AP', 'Andhra Pradesh', 1),
    ('IN-AR', 'Arunachal Pradesh', 2),
    ('IN-AS', 'Assam', 3),
    ('IN-BR', 'Bihar', 4),
    ('IN-CG', 'Chhattisgarh', 5),
    ('IN-GA', 'Goa', 6),
    ('IN-GJ', 'Gujarat', 7),
    ('IN-HR', 'Haryana', 8),
    ('IN-HP', 'Himachal Pradesh', 9),
    ('IN-JH', 'Jharkhand', 10),
    ('IN-KA', 'Karnataka', 11),
    ('IN-KL', 'Kerala', 12),
    ('IN-MP', 'Madhya Pradesh', 13),
    ('IN-MH', 'Maharashtra', 14),
    ('IN-MN', 'Manipur', 15),
    ('IN-ML', 'Meghalaya', 16),
    ('IN-MZ', 'Mizoram', 17),
    ('IN-NL', 'Nagaland', 18),
    ('IN-OD', 'Odisha', 19),
    ('IN-PB', 'Punjab', 20),
    ('IN-RJ', 'Rajasthan', 21),
    ('IN-SK', 'Sikkim', 22),
    ('IN-TN', 'Tamil Nadu', 23),
    ('IN-TS', 'Telangana', 24),
    ('IN-TR', 'Tripura', 25),
    ('IN-UP', 'Uttar Pradesh', 26),
    ('IN-UK', 'Uttarakhand', 27),
    ('IN-WB', 'West Bengal', 28),
    ('IN-AN', 'Andaman and Nicobar Islands', 29),
    ('IN-CH', 'Chandigarh', 30),
    ('IN-DH', 'Dadra and Nagar Haveli and Daman and Diu', 31),
    ('IN-DL', 'Delhi', 32),
    ('IN-JK', 'Jammu and Kashmir', 33),
    ('IN-LA', 'Ladakh', 34),
    ('IN-LD', 'Lakshadweep', 35),
    ('IN-PY', 'Puducherry', 36)
) AS v(code, name, display_order)
WHERE c.code = 'STATE';

-- CITY (India, major cities)
INSERT INTO master_value (category_id, code, name, display_order, metadata)
SELECT c.id, v.code, v.name, v.display_order,
       jsonb_build_object('countryCode', 'IN', 'stateCode', v.state_code)
FROM master_category c
CROSS JOIN (VALUES
    ('MUMBAI', 'Mumbai', 'IN-MH', 1),
    ('PUNE', 'Pune', 'IN-MH', 2),
    ('NAGPUR', 'Nagpur', 'IN-MH', 3),
    ('NEW_DELHI', 'New Delhi', 'IN-DL', 4),
    ('BENGALURU', 'Bengaluru', 'IN-KA', 5),
    ('MYSURU', 'Mysuru', 'IN-KA', 6),
    ('CHENNAI', 'Chennai', 'IN-TN', 7),
    ('COIMBATORE', 'Coimbatore', 'IN-TN', 8),
    ('MADURAI', 'Madurai', 'IN-TN', 9),
    ('HYDERABAD', 'Hyderabad', 'IN-TS', 10),
    ('KOLKATA', 'Kolkata', 'IN-WB', 11),
    ('AHMEDABAD', 'Ahmedabad', 'IN-GJ', 12),
    ('SURAT', 'Surat', 'IN-GJ', 13),
    ('VADODARA', 'Vadodara', 'IN-GJ', 14),
    ('JAIPUR', 'Jaipur', 'IN-RJ', 15),
    ('LUCKNOW', 'Lucknow', 'IN-UP', 16),
    ('NOIDA', 'Noida', 'IN-UP', 17),
    ('VARANASI', 'Varanasi', 'IN-UP', 18),
    ('KOCHI', 'Kochi', 'IN-KL', 19),
    ('THIRUVANANTHAPURAM', 'Thiruvananthapuram', 'IN-KL', 20),
    ('CHANDIGARH', 'Chandigarh', 'IN-CH', 21),
    ('GURUGRAM', 'Gurugram', 'IN-HR', 22),
    ('BHOPAL', 'Bhopal', 'IN-MP', 23),
    ('INDORE', 'Indore', 'IN-MP', 24),
    ('PATNA', 'Patna', 'IN-BR', 25),
    ('BHUBANESWAR', 'Bhubaneswar', 'IN-OD', 26),
    ('VISAKHAPATNAM', 'Visakhapatnam', 'IN-AP', 27),
    ('VIJAYAWADA', 'Vijayawada', 'IN-AP', 28),
    ('GUWAHATI', 'Guwahati', 'IN-AS', 29),
    ('DEHRADUN', 'Dehradun', 'IN-UK', 30),
    ('RISHIKESH', 'Rishikesh', 'IN-UK', 31),
    ('AMRITSAR', 'Amritsar', 'IN-PB', 32),
    ('LUDHIANA', 'Ludhiana', 'IN-PB', 33),
    ('RANCHI', 'Ranchi', 'IN-JH', 34),
    ('RAIPUR', 'Raipur', 'IN-CG', 35),
    ('PANAJI', 'Panaji', 'IN-GA', 36),
    ('SHIMLA', 'Shimla', 'IN-HP', 37),
    ('SRINAGAR', 'Srinagar', 'IN-JK', 38),
    ('JAMMU', 'Jammu', 'IN-JK', 39),
    ('PUDUCHERRY', 'Puducherry', 'IN-PY', 40)
) AS v(code, name, state_code, display_order)
WHERE c.code = 'CITY';

-- Flat categories: (category code, value code, name, display order)
INSERT INTO master_value (category_id, code, name, display_order)
SELECT c.id, v.code, v.name, v.display_order
FROM (VALUES
    ('LANGUAGE', 'ENGLISH', 'English', 1),
    ('LANGUAGE', 'HINDI', 'Hindi', 2),
    ('LANGUAGE', 'TAMIL', 'Tamil', 3),
    ('LANGUAGE', 'TELUGU', 'Telugu', 4),
    ('LANGUAGE', 'KANNADA', 'Kannada', 5),
    ('LANGUAGE', 'MALAYALAM', 'Malayalam', 6),
    ('LANGUAGE', 'MARATHI', 'Marathi', 7),
    ('LANGUAGE', 'BENGALI', 'Bengali', 8),
    ('LANGUAGE', 'GUJARATI', 'Gujarati', 9),
    ('LANGUAGE', 'PUNJABI', 'Punjabi', 10),
    ('LANGUAGE', 'ODIA', 'Odia', 11),
    ('LANGUAGE', 'ASSAMESE', 'Assamese', 12),
    ('LANGUAGE', 'URDU', 'Urdu', 13),
    ('LANGUAGE', 'SANSKRIT', 'Sanskrit', 14),
    ('LANGUAGE', 'KONKANI', 'Konkani', 15),
    ('LANGUAGE', 'KASHMIRI', 'Kashmiri', 16),
    ('LANGUAGE', 'NEPALI', 'Nepali', 17),
    ('LANGUAGE', 'SPANISH', 'Spanish', 18),
    ('LANGUAGE', 'FRENCH', 'French', 19),
    ('LANGUAGE', 'GERMAN', 'German', 20),

    ('RELIGION', 'HINDUISM', 'Hinduism', 1),
    ('RELIGION', 'ISLAM', 'Islam', 2),
    ('RELIGION', 'CHRISTIANITY', 'Christianity', 3),
    ('RELIGION', 'SIKHISM', 'Sikhism', 4),
    ('RELIGION', 'BUDDHISM', 'Buddhism', 5),
    ('RELIGION', 'JAINISM', 'Jainism', 6),
    ('RELIGION', 'JUDAISM', 'Judaism', 7),
    ('RELIGION', 'ZOROASTRIANISM', 'Zoroastrianism', 8),
    ('RELIGION', 'SPIRITUAL_NOT_RELIGIOUS', 'Spiritual, not religious', 9),
    ('RELIGION', 'NO_RELIGION', 'No religion', 10),
    ('RELIGION', 'OTHER', 'Other', 11),

    ('EDUCATION_LEVEL', 'HIGH_SCHOOL', 'High school', 1),
    ('EDUCATION_LEVEL', 'DIPLOMA', 'Diploma', 2),
    ('EDUCATION_LEVEL', 'BACHELORS', 'Bachelor''s degree', 3),
    ('EDUCATION_LEVEL', 'MASTERS', 'Master''s degree', 4),
    ('EDUCATION_LEVEL', 'DOCTORATE', 'Doctorate', 5),
    ('EDUCATION_LEVEL', 'PROFESSIONAL', 'Professional qualification', 6),
    ('EDUCATION_LEVEL', 'OTHER', 'Other', 7),

    ('OCCUPATION', 'SOFTWARE_PROFESSIONAL', 'Software professional', 1),
    ('OCCUPATION', 'ENGINEER', 'Engineer', 2),
    ('OCCUPATION', 'HEALTHCARE_PROFESSIONAL', 'Doctor / healthcare professional', 3),
    ('OCCUPATION', 'TEACHER_PROFESSOR', 'Teacher / professor', 4),
    ('OCCUPATION', 'BUSINESS_OWNER', 'Business owner / entrepreneur', 5),
    ('OCCUPATION', 'FINANCE_ACCOUNTING', 'Finance / accounting professional', 6),
    ('OCCUPATION', 'LEGAL_PROFESSIONAL', 'Legal professional', 7),
    ('OCCUPATION', 'GOVERNMENT_SERVICES', 'Government / civil services', 8),
    ('OCCUPATION', 'DESIGN_CREATIVE', 'Designer / creative professional', 9),
    ('OCCUPATION', 'MEDIA_MARKETING', 'Media / marketing professional', 10),
    ('OCCUPATION', 'SCIENTIST_RESEARCHER', 'Scientist / researcher', 11),
    ('OCCUPATION', 'ARMED_FORCES', 'Armed forces', 12),
    ('OCCUPATION', 'SELF_EMPLOYED', 'Self-employed / freelancer', 13),
    ('OCCUPATION', 'AGRICULTURE', 'Agriculture / farming', 14),
    ('OCCUPATION', 'STUDENT', 'Student', 15),
    ('OCCUPATION', 'HOMEMAKER', 'Homemaker', 16),
    ('OCCUPATION', 'NOT_WORKING', 'Not working', 17),
    ('OCCUPATION', 'OTHER', 'Other', 18),

    ('INDUSTRY', 'IT_SOFTWARE', 'IT & software', 1),
    ('INDUSTRY', 'HEALTHCARE', 'Healthcare', 2),
    ('INDUSTRY', 'EDUCATION', 'Education', 3),
    ('INDUSTRY', 'BANKING_FINANCE', 'Banking & finance', 4),
    ('INDUSTRY', 'MANUFACTURING', 'Manufacturing', 5),
    ('INDUSTRY', 'RETAIL_ECOMMERCE', 'Retail & e-commerce', 6),
    ('INDUSTRY', 'GOVERNMENT_PUBLIC_SECTOR', 'Government & public sector', 7),
    ('INDUSTRY', 'MEDIA_ENTERTAINMENT', 'Media & entertainment', 8),
    ('INDUSTRY', 'HOSPITALITY_TRAVEL', 'Hospitality & travel', 9),
    ('INDUSTRY', 'REAL_ESTATE_CONSTRUCTION', 'Real estate & construction', 10),
    ('INDUSTRY', 'AGRICULTURE', 'Agriculture', 11),
    ('INDUSTRY', 'LEGAL_SERVICES', 'Legal services', 12),
    ('INDUSTRY', 'CONSULTING', 'Consulting', 13),
    ('INDUSTRY', 'TELECOMMUNICATIONS', 'Telecommunications', 14),
    ('INDUSTRY', 'ENERGY_UTILITIES', 'Energy & utilities', 15),
    ('INDUSTRY', 'NON_PROFIT_SOCIAL_WORK', 'Non-profit & social work', 16),
    ('INDUSTRY', 'OTHER', 'Other', 17),

    ('MARITAL_STATUS', 'NEVER_MARRIED', 'Never married', 1),
    ('MARITAL_STATUS', 'DIVORCED', 'Divorced', 2),
    ('MARITAL_STATUS', 'WIDOWED', 'Widowed', 3),
    ('MARITAL_STATUS', 'SEPARATED', 'Separated', 4),

    ('DIET', 'VEGETARIAN', 'Vegetarian', 1),
    ('DIET', 'VEGAN', 'Vegan', 2),
    ('DIET', 'EGGETARIAN', 'Eggetarian', 3),
    ('DIET', 'NON_VEGETARIAN', 'Non-vegetarian', 4),
    ('DIET', 'JAIN', 'Jain', 5),
    ('DIET', 'PESCATARIAN', 'Pescatarian', 6),

    ('SMOKING', 'NEVER', 'Never', 1),
    ('SMOKING', 'OCCASIONALLY', 'Occasionally', 2),
    ('SMOKING', 'REGULARLY', 'Regularly', 3),
    ('SMOKING', 'TRYING_TO_QUIT', 'Trying to quit', 4),

    ('DRINKING', 'NEVER', 'Never', 1),
    ('DRINKING', 'OCCASIONALLY', 'Occasionally', 2),
    ('DRINKING', 'SOCIALLY', 'Socially', 3),
    ('DRINKING', 'REGULARLY', 'Regularly', 4),

    ('EXERCISE_FREQUENCY', 'NEVER', 'Never', 1),
    ('EXERCISE_FREQUENCY', 'RARELY', 'Rarely', 2),
    ('EXERCISE_FREQUENCY', 'WEEKLY', '1-2 times a week', 3),
    ('EXERCISE_FREQUENCY', 'FREQUENTLY', '3-5 times a week', 4),
    ('EXERCISE_FREQUENCY', 'DAILY', 'Daily', 5),

    ('INTEREST', 'SPIRITUALITY', 'Spirituality', 1),
    ('INTEREST', 'MEDITATION', 'Meditation', 2),
    ('INTEREST', 'YOGA', 'Yoga', 3),
    ('INTEREST', 'PHILOSOPHY', 'Philosophy', 4),
    ('INTEREST', 'PERSONAL_GROWTH', 'Personal growth', 5),
    ('INTEREST', 'HEALTH_WELLNESS', 'Health & wellness', 6),
    ('INTEREST', 'TRAVEL', 'Travel', 7),
    ('INTEREST', 'NATURE', 'Nature & outdoors', 8),
    ('INTEREST', 'MUSIC', 'Music', 9),
    ('INTEREST', 'MOVIES', 'Movies & series', 10),
    ('INTEREST', 'BOOKS', 'Books', 11),
    ('INTEREST', 'ART', 'Art & culture', 12),
    ('INTEREST', 'FOOD', 'Food', 13),
    ('INTEREST', 'TECHNOLOGY', 'Technology', 14),
    ('INTEREST', 'SPORTS', 'Sports', 15),
    ('INTEREST', 'ENTREPRENEURSHIP', 'Entrepreneurship', 16),
    ('INTEREST', 'ENVIRONMENT', 'Environment & sustainability', 17),
    ('INTEREST', 'VOLUNTEERING', 'Volunteering', 18),

    ('HOBBY', 'READING', 'Reading', 1),
    ('HOBBY', 'WRITING', 'Writing / journaling', 2),
    ('HOBBY', 'PAINTING', 'Painting / drawing', 3),
    ('HOBBY', 'SINGING', 'Singing', 4),
    ('HOBBY', 'INSTRUMENT', 'Playing an instrument', 5),
    ('HOBBY', 'DANCING', 'Dancing', 6),
    ('HOBBY', 'COOKING', 'Cooking', 7),
    ('HOBBY', 'GARDENING', 'Gardening', 8),
    ('HOBBY', 'PHOTOGRAPHY', 'Photography', 9),
    ('HOBBY', 'TREKKING', 'Trekking / hiking', 10),
    ('HOBBY', 'CYCLING', 'Cycling', 11),
    ('HOBBY', 'RUNNING', 'Running', 12),
    ('HOBBY', 'SWIMMING', 'Swimming', 13),
    ('HOBBY', 'CHESS', 'Chess / board games', 14),
    ('HOBBY', 'CRAFTS', 'Crafts / DIY', 15),
    ('HOBBY', 'TEAM_SPORTS', 'Team sports', 16)
) AS v(category_code, code, name, display_order)
JOIN master_category c ON c.code = v.category_code;
