-- New table for POST /appeals (Trust & Safety). Not in the original V1 schema - added now because the
-- endpoint was previously deferred pending this exact decision. type is left as free text (no CHECK
-- constraint), same treatment as notification.type and support_ticket.category: it's a client-supplied
-- category this backend has no authority to enumerate. status is a real workflow the backend reasons about
-- (admin approve/reject), so it does get a CHECK constraint, same as report/moderation/support_ticket.

CREATE TABLE appeal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    type VARCHAR(50) NOT NULL,
    details TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    resolution_notes TEXT,
    resolved_by BIGINT REFERENCES "user" (id),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_appeal_status CHECK (status IN ('OPEN', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_appeal_user ON appeal (user_id, created_at);
CREATE INDEX idx_appeal_status ON appeal (status, created_at);
