-- New table for GET /discovery/collections and GET /discovery/collections/{collectionId}. Not in the original
-- V1 schema - added now because the endpoint was previously deferred pending this exact decision.
--
-- Design: a collection is a named, admin-curated filter (criteria JSONB, same shape as a DiscoverySearchRequest
-- minus page/size) rather than a table of stored profile ids. Membership is computed at read time by running
-- that criteria through the same Specification-building code browse()/search() already use, so a collection
-- never goes stale and adding one is a data change, not a code change. code is the path identifier
-- (collectionId is typed as a plain string in the contract, not a uuid) - unique and stable, e.g. "new-members".
CREATE TABLE discovery_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    criteria JSONB,
    display_order SMALLINT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_discovery_collection_active ON discovery_collection (is_active, display_order);
